steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - gcloud
      - functions
      - deploy
      - dynamic-dns-update
      - --allow-unauthenticated
      - --entry-point=main
      - --env-vars-file=env.yaml
      - --memory=128MB
      - --region=europe-west6
      - --runtime=python39
      - --trigger-http
